core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns= [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetalharServicoView.as_view(), name='detalhe_servico')
]

fabricasites/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from stdimage.models import  StdImageField


class Base(models.Model):
    criado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True)
    ativo = models.BooleanField(default=True)

    class Meta:
        abstract = True


class Cargo(models.Model):
    cargo = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Cargo'
        verbose_name_plural = 'Cargos'

        def __str__(self):
            return self.cargo

class Funcionario(Base):
    nome = models.CharField('Nome', max_length=255)
    biografia = models.TextField('Bio', max_length=1000)
    cargo = models.ForeignKey('core.Cargo', on_delete=models.SET_NULL, null=True )
    foto = StdImageField('Foto', upload_to='equipe',
                         variations= {'thumb': {'width': 600,
                                                'height': 600,
                                                'crop': True}})
    facebook = models.CharField('Face', max_length=100, default='#')
    twitter = models.CharField('Twitter', max_length=100, default='#')
    instagram = models.CharField('Insta', max_length=100, default='#')

    class Meta:
        verbose_name = 'Funcionário'
        verbose_name_plural = 'Funcionários'


    def __str__(self):
        return self.nome


class Servico(Base):
    imagem = StdImageField('Imagem', upload_to='servicos',
                           variations={'thumb': {'width': 1000,
                                                 'height': 667,
                                                 'crop': True}})
    nome = models.CharField('Nome', max_length=50)
    descricao = models.TextField('Descricao', max_length=500)

    class Meta:
        verbose_name = 'Serviço'
        verbose_name_plural = 'Serviços'

    def __str__(self):
        return self.nome

core/forms.py
from django import forms
from django.core.mail.message import  EmailMessage


class ContatoForm(forms.Form):
    nome = forms.CharField(label='Nome', max_length=100)
    email = forms.EmailField(label='Email', max_length=100)
    telefone = forms.CharField(label='Telefone', max_length=20)
    mensagem = forms.CharField(label='Mensagem', widget= forms.Textarea())

    def send_mail(self):
        nome = self.cleaned_data['nome']
        email = self.cleaned_data['email']
        telefone = self.cleaned_data['telefone']
        mensagem = self.cleaned_data['mensagem']

        conteudo = f'de: {nome}\n' \
                    f'{mensagem}'

        mail = EmailMessage(
            subject='contato: ' + nome,
            body= conteudo,
            from_email= 'contato@Fabricasites.com.br',
            to=['contato@fabricasites.com.br',],
            headers={'Reply-To': email}
        )
        mail.send()

core/views.py
from django.views.generic import FormView, DetailView
from django.urls import reverse_lazy
from django.contrib import messages

from .models import Funcionario, Servico
from .forms import ContatoForm


class IndexView(FormView):
    template_name = 'index.html'
    form_class = ContatoForm
    success_url = reverse_lazy('core:index')

    #sobreescrevendo o  método de obtenção do contexto
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['funcionarios'] = Funcionario.objects.order_by('?').all()
        context['servicos'] = Servico.objects.order_by('?').all()
        return context

    def form_valid(self, form, *args, **kwargs):
        form.send_mail()
        messages.success(self.request, 'Email enviado com sucesso!!!')
        return super(IndexView, self).form_valid(form, *args, *kwargs)

    def form_invalid(self, form, *args, **kwargs):
        messages.error(self.request,'Erro ao enviar o email.')
        return super(IndexView, self).form_invalid(form, *args, *kwargs)


class DetalharServicoView(DetailView):
    template_name = 'detalhe_servico.html'
    model = Servico

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html  >
<head>
  <!-- Site made with Mobirise Website Builder v5.2.0, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v5.2.0, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="{% static 'images/mbr-94x87.png' %}" type="image/x-icon">
  <meta name="description" content="">


  <title>Fábrica de Sites</title>
  <link rel="stylesheet" href="{% static 'tether/tether.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'dropdown/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'formstyler/jquery.formstyler.css' %}">
  <link rel="stylesheet" href="{% static 'formstyler/jquery.formstyler.theme.css' %}">
  <link rel="stylesheet" href="{% static 'datepicker/jquery.datetimepicker.min.css' %}">
  <link rel="stylesheet" href="{% static 'socicon/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'theme/css/style.css' %}">
  <link rel="preload" as="style" href="{% static 'mobirise/css/mbr-additional.css' %}"><link rel="stylesheet" href="{% static 'mobirise/css/mbr-additional.css' %}" type="text/css">




</head>
<body>

  <section class="menu cid-s48OLK6784" once="menu" id="menu1-k">

    <nav class="navbar navbar-dropdown navbar-fixed-top navbar-expand-lg">
        <div class="container">
            <div class="navbar-brand">
                <span class="navbar-logo">
                    <a href="{% url 'core:index' %}">
                        <img src="{% static 'images/mbr-94x87.png' %}" alt="logotipo" style="height: 3.8rem;">
                    </a>
                </span>
                <span class="navbar-caption-wrap"><a class="navbar-caption text-black display-7" href="{% url 'core:index' %}">Fábrica de Sites</a></span>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <div class="hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true"><li class="nav-item"><a class="nav-link link text-black text-primary display-4" href="{% url 'core:index' %}#top">
                            Topo<br></a></li><li class="nav-item"><a class="nav-link link text-black text-primary display-4" href="{% url 'core:index' %}#features3-s">Nossos Serviços</a></li>
                    <li class="nav-item"><a class="nav-link link text-black text-primary display-4" href="{% url 'core:index' %}#team1-p">
                            Nossa Equipe</a></li></ul>


            </div>
        </div>
    </nav>

</section>

{% block conteudo %}{% endblock %}

<section class="footer3 cid-s48P1Icc8J" once="footers" id="footer3-l">

    <div class="container">
        <div class="media-container-row align-center mbr-white">
            <div class="row row-links">
                <ul class="foot-menu">

                <li class="foot-menu-item mbr-fonts-style display-7"><a href="https://mobirise.com/help/" class="text-success">Help Center</a></li><li class="foot-menu-item mbr-fonts-style display-7"><a href="https://mobirise.com/help/" class="text-success">Help Center</a></li></ul>
            </div>
            <div class="row social-row">
                <div class="social-list align-right pb-2">


                <div class="soc-item">
                        <a href="https://twitter.com/mobirise" target="_blank">
                            <span class="socicon-twitter socicon mbr-iconfont mbr-iconfont-social"></span>
                        </a>
                    </div><div class="soc-item">
                        <a href="https://twitter.com/mobirise" target="_blank">
                            <span class="socicon-twitter socicon mbr-iconfont mbr-iconfont-social"></span>
                        </a>
                    </div><div class="soc-item">
                        <a href="https://twitter.com/mobirise" target="_blank">
                            <span class="socicon-twitter socicon mbr-iconfont mbr-iconfont-social"></span>
                        </a>
                    </div></div>
            </div>
            <div class="row row-copirayt">
                <p class="mbr-text mb-0 mbr-fonts-style mbr-white align-center display-7">
                    © Copyright 2020 IFRO. All Rights Reserved.
                </p>
            </div>
        </div>
    </div>
</section><section style="background-color: #fff; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Helvetica Neue', Arial, sans-serif; color:#aaa; font-size:12px; padding: 0; align-items: center; display: flex;"><a href="https://mobirise.site/q" style="flex: 1 1; height: 3rem; padding-left: 1rem;"></a><p style="flex: 0 0 auto; margin:0; padding-right:1rem;"><a href="https://mobirise.site/r" style="color:#aaa;">This page</a> was created with Mobirise template</p></section><script src="{% static 'web/assets/jquery/jquery.min.js' %}"></script>  <script src="{% static 'popper/popper.min.js' %}"></script>  <script src="{% static 'tether/tether.min.js' %}"></script>  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>  <script src="{% static 'smoothscroll/smooth-scroll.js' %}"></script>  <script src="{% static 'dropdown/js/nav-dropdown.js' %}"></script>  <script src="{% static 'dropdown/js/navbar-dropdown.js' %}"></script>  <script src="{% static 'touchswipe/jquery.touch-swipe.min.js' %}"></script>  <script src="{% static 'formstyler/jquery.formstyler.js' %}"></script>  <script src="{% static 'formstyler/jquery.formstyler.min.js' %}"></script>  <script src="{% static 'datepicker/jquery.datetimepicker.full.js' %}"></script>  <script src="{% static 'theme/js/script.js' %}"></script>  <script src="{% static 'formoid/formoid.min.js' %}"></script>


</body>
</html>

core/templates/cabecalho.html
{% load static %}
<section class="header18 cid-sunwLq52tG mbr-fullscreen" id="header18-n">


    <div class="align-center container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-10">
                <h1 class="mbr-section-title mbr-fonts-style mbr-white mb-3 display-1"><strong>Conheça minha empresa e se apaixone!</strong></h1>

                <p class="mbr-text mbr-fonts-style mbr-white display-7">
                    Aqui você vai encontrar os mais diversos tipos de serviços para você tirar do papel aquela sua ideia transformando-a em realidade hoje mesmo.</p>

            </div>
        </div>
    </div>
</section>

core/templates/detalhe_servico.html
{% extends 'base.html' %}
{% load static %}

{% block conteudo %}
    <div class="container">
        <div class="item-img">
            <img src="{{ servico.imagem.thumb.url }}" alt="imagem serviço"
            width="500" height="333">
        </div>
        <div class="container">
            <h1> {{ servico.nome }} </h1>
            <p>{{ servico.descricao }}</p>
        </div>
    </div>
{% endblock %}

core/templates/equipe.html
{% load static %}
<section class="team1 cid-sunxGubk5K" id="team1-p">

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
                <h3 class="mbr-section-title mbr-fonts-style align-center mb-4 display-2">
                    <strong>Nossa Equipe</strong></h3>

            </div>

            {% for f in funcionarios %}
            <div class="col-sm-6 col-lg-4">
                <div class="card-wrap">
                    <div class="image-wrap">
                        <img src="{{ f.foto.thumb.url }}">
                    </div>
                    <div class="content-wrap">
                        <h5 class="mbr-section-title card-title mbr-fonts-style align-center m-0 display-5">
                            <strong>{{ f.nome }}</strong>
                        </h5>
                        <h6 class="mbr-role mbr-fonts-style align-center mb-3 display-4">
                            <strong>{{ f.cargo }}</strong>
                        </h6>
                        <p class="card-text mbr-fonts-style align-center display-7">
                            {{ f.biografia }}
                        </p>
                        <div class="social-row display-7">
                            <div class="soc-item">
                                <a href="{{ f.facebook }}" target="_blank">
                                    <span class="mbr-iconfont socicon socicon-facebook"></span>
                                </a>
                            </div>
                            <div class="soc-item">
                                <a href="{{ f.twitter }}" target="_blank">
                                    <span class="mbr-iconfont socicon socicon-twitter"></span>
                                </a>
                            </div>
                            <div class="soc-item">
                                <a href="{{ f.instagram }}" target="_blank">
                                    <span class="mbr-iconfont socicon socicon-instagram"></span>
                                </a>
                            </div>

                        </div>

                    </div>
                </div>
            </div>
            {% endfor %}


        </div>
    </div>
</section>

core/templates/formulario.html
{% load static %}
<section class="form6 cid-sunxTcEbC6" id="form6-q">


    <div class="container">
        <div class="mbr-section-head">
            <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                <strong>Entre em contato</strong></h3>

        </div>
        <div class="row justify-content-center mt-4">
            <div class="col-lg-8 mx-auto mbr-form" >
                <form action="{% url 'core:index' %}#form6-q" method="POST" class="mbr-form form-with-styler mx-auto">
                    {% csrf_token %}
                    <div class="container">
                        {% if messages %}
                            {% for m in messages %}
                                <div class="alert alert-{{ m.tags}} col-12">
                                    {{ m }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="dragArea row">
                        <div class="col-lg-12 col-md-12 col-sm-12 form-group">
                            <input type="text" name="nome" placeholder="Nome" class="form-control" value="" id="name-form6-q">
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 form-group" data-for="email">
                            <input type="email" name="email" placeholder="E-mail" class="form-control" value="" id="email-form6-q">
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 form-group">
                            <input type="tel" name="telefone" placeholder="Telefone" class="form-control" value="" id="phone-form6-q">
                        </div>
                        <div data-for="mensagem" class="col-lg-12 col-md-12 col-sm-12 form-group">
                            <textarea placeholder="Mensagem" name="mensagem" class="form-control" value="" id="mensagem-form6-q"></textarea>
                        </div>

                        <div class="col-auto mbr-section-btn align-center">
                            <button type="submit" class="btn btn-primary display-4">Enviar Email</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

core/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block conteudo %}

    {% include 'cabecalho.html' %}
    {% include 'servicos.html' %}
    {% include 'equipe.html' %}
    {% include 'formulario.html' %}

{% endblock %}

core/templates/servicos.html
{% load static %}
<section class="features3 cid-sunCqvmC9x" id="features3-s">

    <div class="container">
        <div class="mbr-section-head">
            <h4 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                <strong>Nossos Serviços</strong></h4>

        </div>
        <div class="row mt-4 justify-content-center">
            {% for s in servicos %}
            <div class="item features-image сol-12 col-md-6 col-lg-4">
                <div class="item-wrapper">
                    <div class="item-img">
                        <img src="{{ s.imagem.thumb.url }} ">
                    </div>
                    <div class="item-content">
                        <h5 class="item-title mbr-fonts-style display-7">
                            <strong>{{ s.nome }}</strong></h5>

                        <p class="mbr-text mbr-fonts-style mt-3 display-7">
                            {{ s.descricao| truncatewords:10 }}</p>
                    </div>
                    <div class="mbr-section-btn item-footer mt-2">
                        <a href="{% url 'core:detalhe_servico' s.id %}" class="btn btn-primary item-btn display-7" target="_blank">
                        Leia Mais
                            &gt;</a></div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</section>